### ISSUE TITLE
代码再次predict的时候f1 为0 ？

### ISSUE THREAD

**Issue by WaNePr** [swy0915/BERT-BiLSTM-CRF-NER#1]
python3 bert_lstm_ner.py --do_train=False --do_eval=False --do_predict=True --data_dir=data1/ --predict_batch_siz=16  --output_dir=result_blc1_copy --dropout_rate=1 

<img width="484" alt="Screenshot 2019-03-12 at 15 51 19" src="https://user-images.githubusercontent.com/17458069/54183259-b44ec380-44de-11e9-872e-0bf390746e7c.png">

predict出来的f1为0， 但是正常和train，eval，test一起计算出来的显示正常

**Comment by swy0915** [comment]
可能代码里有点小问题 自行修改吧
