### ISSUE TITLE
额 请问label2id.pkl文件 和 data.conf文件在哪

### ISSUE THREAD

**Issue by shijintong** [swy0915/BERT-BiLSTM-CRF-NER#2]
请问label2id.pkl文件 和 data.conf文件在哪

**Comment by swy0915** [comment]
自动生成的

**Comment by shijintong** [comment]
训练之前配置好了参数和路径&nbsp; 但训练结束之后出现这个问题 precision和recall是nan&nbsp; 缺少data.conf




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swy0915/BERT-BiLSTM-CRF-NER"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 中午1:45
收件人:&nbsp;"swy0915/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;;
抄送:&nbsp;"Treasure"<770851479@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swy0915/BERT-BiLSTM-CRF-NER] 额 请问label2id.pkl文件 和 data.conf文件在哪 (#2)





 
自动生成的
